################################################################################
#
#  Software License Agreement (BSD License)
#  Copyright (c) 2003-2024, CHAI3D
#  (www.chai3d.org)
#
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#
#  * Redistributions of source code must retain the above copyright
#  notice, this list of conditions and the following disclaimer.
#
#  * Redistributions in binary form must reproduce the above
#  copyright notice, this list of conditions and the following
#  disclaimer in the documentation and/or other materials provided
#  with the distribution.
#
#  * Neither the name of CHAI3D nor the names of its contributors may
#  be used to endorse or promote products derived from this software
#  without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
#  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
#  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
################################################################################

# Enable ('yes') or disable ('no') support for CHAI3D features that are based on
# external libraries (e.g. file format support).

CHAI3D_USE_GIFLIB       ?= yes
CHAI3D_USE_LIB3DS       ?= yes
CHAI3D_USE_LIBJPEG      ?= yes
CHAI3D_USE_LIBPNG       ?= yes
CHAI3D_USE_OPENAL       ?= yes
CHAI3D_USE_PUGIXML      ?= yes
CHAI3D_USE_RTMIDI       ?= yes
CHAI3D_USE_THEORAPLAYER ?= yes

# Edit configuration variables for each external library:
# 'no'  builds CHAI3D with built-in support for that particular library
# 'yes' builds CHAI3D against your local system versions of the library

# External libraries used by the chai3d library
CHAI3D_USE_EXTERNAL_GIFLIB       ?= no
CHAI3D_USE_EXTERNAL_LIB3DS       ?= no
CHAI3D_USE_EXTERNAL_LIBJPEG      ?= no
CHAI3D_USE_EXTERNAL_LIBPNG       ?= no
CHAI3D_USE_EXTERNAL_OPENAL       ?= no
CHAI3D_USE_EXTERNAL_PUGIXML      ?= no
CHAI3D_USE_EXTERNAL_RTMIDI       ?= no
CHAI3D_USE_EXTERNAL_THEORAPLAYER ?= no

# External libraries used by the chai3d example applications
CHAI3D_USE_EXTERNAL_GLFW         ?= no
