// version info
#define CHAI3D_BULLET_DESCRIPTION     "Bullet wrapper module for CHAI3D"
#define CHAI3D_BULLET_VERSION_MAJOR   1
#define CHAI3D_BULLET_VERSION_MINOR   0
#define CHAI3D_BULLET_VERSION_PATCH   0
#define CHAI3D_BULLET_PRERELEASE      ""
#define CHAI3D_BULLET_METADATA        "+g9f2e2b0b2"
#define CHAI3D_BULLET_VERSION         "1.0.0"
#define CHAI3D_BULLET_VERSION_FULL    "1.0.0+g9f2e2b0b2"
#define CHAI3D_BULLET_REVISION        0x9f2e2b0b2
