name: 'Build'
description: 'Builds the repository'

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install libeigen3-dev libasound2-dev libusb-1.0.0-dev freeglut3-dev xorg-dev libglew-dev libopenal-dev

    - name: Build Chai3d
      shell: bash
      run: |
        mkdir build && cd build
        cmake .. && make -j8

    - name: Check build status
      shell: bash
      run: |
        cd build
        make --always-make --dry-run