name: Build master and upload artifact on a schedule

on:
  schedule:
    - cron: "0 0 1 * *"
      branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-archive:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: build-repo
        uses: ./.github/actions/build-repo

      - name: Archive chai3d Artifact
        uses: actions/upload-artifact@v3
        with:
          name: chai3d-artifact
          path: build/libchai3d.a